kind: Cluster
apiVersion: clusterregistry.k8s.io/v1alpha1
metadata:
  name: cluster-east
  labels:
    location: cluster-east
---
kind: Cluster
apiVersion: clusterregistry.k8s.io/v1alpha1
metadata:
  name: cluster-west
  labels:
    location: cluster-west
---
kind: ClusterSelector
apiVersion: configmanagement.gke.io/v1
metadata:
  name: cluster-east
spec:
  selector:
    matchLabels:
      location: cluster-east
---
kind: ClusterSelector
apiVersion: configmanagement.gke.io/v1
metadata:
  name: cluster-west
spec:
  selector:
    matchLabels:
      location: cluster-west
