apiVersion: networking.gke.io/v1
kind: MultiClusterService
metadata:
  name: mci-external
  annotations:
    configmanagement.gke.io/cluster-selector: cluster-east
spec:
  template:
    spec:
      selector:
        test: service
        #serviceType: MCIExternal
      ports:
        - name: web
          protocol: TCP
          port: 80
          targetPort: 8080
---
apiVersion: networking.gke.io/v1
kind: MultiClusterIngress
metadata:
  name: mci-external
  annotations:
    configmanagement.gke.io/cluster-selector: cluster-east
spec:
  template:
    spec:
      backend:
        serviceName: mci-external
        servicePort: 80
