apiVersion: v1
kind: Service
metadata:
  name: node-port
spec:
  type: NodePort
  selector:
    test: service
    serviceType: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
